# =============================================================
# HANDS-ON 5 — Your First Real MCP Server
# =============================================================
#
# WHAT THIS TEACHES:
#   - FastMCP — the decorator-based way to build an MCP server
#   - @mcp.tool() — turning a plain function into an MCP tool
#   - How type hints become the tool's parameter schema automatically
#   - mcp.run() — starting the server so MCP clients can connect
#
# THIS IS A REAL, RUNNABLE MCP SERVER.
#
# REQUIREMENTS:
#   pip install mcp
#
# HOW TO RUN:
#   python insurance_server.py
#
# WHAT HAPPENS WHEN YOU RUN IT:
#   The server starts and waits for an MCP CLIENT to connect
#   over stdio (standard input/output). It will look like the
#   terminal is "stuck" — that's normal, it's listening.
#   Press Ctrl+C to stop it.
#
# HOW TO TEST IT (two options):
#   Option A: Use the MCP Inspector (official testing tool):
#     npx @modelcontextprotocol/inspector python insurance_server.py
#     (requires Node.js — opens a browser UI to test your tools)
#
#   Option B: Connect a real MCP client (Hands-on 9+ in this series
#     uses direct function calls instead, to keep things simple
#     without requiring a separate client process)
# =============================================================
 
from mcp.server.fastmcp import FastMCP
 
 
# -------------------------------------------------------------
# STEP 1: Create the MCP Server
# -------------------------------------------------------------
# FastMCP("name") creates a server instance.
# The name shows up when clients discover this server.
# -------------------------------------------------------------
 
mcp = FastMCP("Insurance Server")
 
 
# -------------------------------------------------------------
# STEP 2: Define a Tool with @mcp.tool()
# -------------------------------------------------------------
# The decorator does the work Hands-on 3 did manually:
#   - Reads the function name -> becomes the tool name
#   - Reads the docstring -> becomes the tool description
#   - Reads type hints (policy_id: str) -> becomes the parameter schema
#   - Reads the return type (-> str) -> becomes the output schema
#
# This is the SAME claim/policy example from Hands-on 1 and 3,
# now wired into a real MCP server.
# -------------------------------------------------------------
 
@mcp.tool()
def get_policy(policy_id: str) -> str:
    """Get insurance policy type by policy ID."""
    policies = {
        "P1001": "Health Insurance",
        "P1002": "Car Insurance",
        "P1003": "Life Insurance",
    }
    return policies.get(policy_id, "Not Found")
 
 
# -------------------------------------------------------------
# STEP 3: Start the Server
# -------------------------------------------------------------
# mcp.run() starts listening for MCP client connections.
# By default this uses "stdio" transport — the standard way
# MCP servers communicate with local AI hosts like Claude Desktop.
# -------------------------------------------------------------
 
if __name__ == "__main__":
    print("Starting Insurance MCP Server...")
    print("Tool available: get_policy(policy_id)")
    print("Waiting for MCP client connections (Ctrl+C to stop)...\n")
    mcp.run()
 
 
# =============================================================
# WHAT TO EXPECT WHEN YOU RUN THIS:
#
#   $ python insurance_server.py
#   Starting Insurance MCP Server...
#   Tool available: get_policy(policy_id)
#   Waiting for MCP client connections (Ctrl+C to stop)...
#
#   (terminal appears to hang — this is correct, it's listening)
#
# CONCEPT CHECKPOINT:
#
#   Q: Compare this to Hands-on 3's hand-built schema. What's
#      generated automatically now?
#   A: name="get_policy" (from function name), description
#      (from docstring), parameters={"policy_id": {"type":"string"}}
#      (from the type hint) — all auto-generated by @mcp.tool().
#
#   Q: Why does the terminal look "stuck" after running?
#   A: The server is running and listening for a client to
#      connect over stdio. This is expected behaviour, not a bug.
#
#   Q: What is "stdio transport"?
#   A: MCP servers can communicate over different transports.
#      stdio (standard input/output) is the simplest — used when
#      an AI host launches your server as a subprocess.
#
# CHALLENGE:
#   Add a docstring parameter description using this format and
#   see how it changes the generated schema:
#
#   def get_policy(policy_id: str) -> str:
#       """
#       Get insurance policy type by policy ID.
#
#       Args:
#           policy_id: The unique policy identifier, e.g. P1001
#       """
# =============================================================
 